on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myspringbootdemoapp.azurecr.io
        username: ${{ secrets.acr_myspringbootdemoapp_username }}
        password: ${{ secrets.acr_myspringbootdemoapp_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myspringbootdemoapp.azurecr.io/myakscluster:${{ github.sha }}
        docker push myspringbootdemoapp.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclustere4d3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclustere4d3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclustere4d3
        container-registry-url: myspringbootdemoapp.azurecr.io
        container-registry-username: ${{ secrets.acr_myspringbootdemoapp_username }}
        container-registry-password: ${{ secrets.acr_myspringbootdemoapp_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: myaksclustere4d3
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myspringbootdemoapp.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth